name: my deploy

on:
  push:
    branches:
      - main

jobs:
  MyStep1:
    runs-on: ubuntu-latest

    steps:
    - name: Download repo
      uses: actions/checkout@v3
      
    - name: check?
      run: pwd
  
  MeStep2:
    runs-on: ubuntu-latest
    needs: MyStep1

    steps:
      - name: whoami?
        run: whoami

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  "AKIAX7KWAWWCFKKBGSGT"
          aws-secret-access-key:  "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"
          aws-region           :  "eu-central-1"

      - name: aws cli test
        run: cli s3 ls