name: my deploy

on:
  push:
    branches:
      - main

jobs:
  MyStep1:
    runs-on: ubuntu-latest
    steps:
    - name: Download repo
      uses: actions/checkout@v3
      
    - name: check?
      run: pwd