name: My Second deploy

on:
  push:
    branches:
      - main

jobs:
  Step1:
    runs-on: ubuntu-latest

    steps:
    - name: Download repo
      uses: actions/checkout@v3
  
  Step2:
    runs-on: ubuntu-latest
    needs: Step1

    steps:
      - name: whoami?
        run: whoami

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ""
          aws-secret-access-key:  ""
          aws-region           :  "eu-central-1"

      - name: aws cli test
        run: aws s3 ls
